# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
TraceReg <- function(X, y, lambda, B_init, B, gamma = 0.1, MAXIT = 1e4L, eps = 1e-2, quiet = TRUE) {
    .Call(`_RobustLRL_TraceReg`, X, y, lambda, B_init, B, gamma, MAXIT, eps, quiet)
}

#' @export
deSubGD_single <- function(X, y, d1, d2, adjacency_matrix, B_init, betaT, tau, T = 20L, a = 3.5, b = 0.51, lambda = 1e-2, eps = 1e-2, quiet = TRUE) {
    .Call(`_RobustLRL_deSubGD_single`, X, y, d1, d2, adjacency_matrix, B_init, betaT, tau, T, a, b, lambda, eps, quiet)
}

#' @export
deSubGD <- function(X, y, d1, d2, adjacency_matrix, B_init, betaT, T = 20L, a = 3.5, b = 0.51, tau = 0.5, nlambda = 100L, lambda_factor = 1e-4, lambda_max = 1, eps = 1e-2, quiet = TRUE) {
    .Call(`_RobustLRL_deSubGD`, X, y, d1, d2, adjacency_matrix, B_init, betaT, T, a, b, tau, nlambda, lambda_factor, lambda_max, eps, quiet)
}

#' @export
deTraceReg <- function(X, y, d1, d2, adjacency_matrix, B_init, betaT, T_inner = 20L, tau_penalty_factor = 1 / 6, nlambda = 100L, lambda_factor = 1e-4, lambda_max = 1, quiet = TRUE) {
    .Call(`_RobustLRL_deTraceReg`, X, y, d1, d2, adjacency_matrix, B_init, betaT, T_inner, tau_penalty_factor, nlambda, lambda_factor, lambda_max, quiet)
}

#' @export
decentralizedTraceQR_inner <- function(X, yt, adjacency_matrix, rho, omega, B_outer, tau_penalty, lambda = 0.015, T_inner = 20L) {
    .Call(`_RobustLRL_decentralizedTraceQR_inner`, X, yt, adjacency_matrix, rho, omega, B_outer, tau_penalty, lambda, T_inner)
}

#' @export
decentralizedTraceQR_cpp <- function(X, y, d1, d2, adjacency_matrix, B_init, betaT, s, tau = 0.5, T_outer = 10L, T_inner = 20L, c0 = 0.1, tau_penalty_factor = 1 / 6, nlambda = 100L, lambda_factor = 1e-4, lambda_max = 1, quiet = TRUE) {
    .Call(`_RobustLRL_decentralizedTraceQR_cpp`, X, y, d1, d2, adjacency_matrix, B_init, betaT, s, tau, T_outer, T_inner, c0, tau_penalty_factor, nlambda, lambda_factor, lambda_max, quiet)
}

#' @export
decentralizedTraceQR_lambda_cpp <- function(X, y, d1, d2, adjacency_matrix, B_init, betaT, s, tau = 0.5, T_outer = 1L, T_inner = 20L, c0 = 0.1, tau_penalty_factor = 1 / 6, f0 = 1, lambda = 0.05, quiet = TRUE) {
    .Call(`_RobustLRL_decentralizedTraceQR_lambda_cpp`, X, y, d1, d2, adjacency_matrix, B_init, betaT, s, tau, T_outer, T_inner, c0, tau_penalty_factor, f0, lambda, quiet)
}

#' @export
decentralizedTraceQR_local_cpp <- function(X, y, d1, d2, adjacency_matrix, B_init, betaT, s, tau = 0.5, T_outer = 10L, T_inner = 20L, c0 = 0.1, tau_penalty_factor = 1 / 6, nlambda = 100L, lambda_factor = 1e-4, lambda_max = 1, quiet = TRUE) {
    .Call(`_RobustLRL_decentralizedTraceQR_local_cpp`, X, y, d1, d2, adjacency_matrix, B_init, betaT, s, tau, T_outer, T_inner, c0, tau_penalty_factor, nlambda, lambda_factor, lambda_max, quiet)
}

#' @export
mQR <- function(X, y, tau, lambda, B_init, B, gamma = 0.1, MAXIT = 1e4L, eps = 1e-2, quiet = TRUE) {
    .Call(`_RobustLRL_mQR`, X, y, tau, lambda, B_init, B, gamma, MAXIT, eps, quiet)
}

#' RcppArmadillo implementation of the R pmax()
NULL

pmax_arma <- function(x, bound) {
    .Call(`_RobustLRL_pmax_arma`, x, bound)
}

kernel <- function(E, h) {
    .Call(`_RobustLRL_kernel`, E, h)
}

mod <- function(v) {
    .Call(`_RobustLRL_mod`, v)
}

quantile_lossCPP <- function(x, tau) {
    .Call(`_RobustLRL_quantile_lossCPP`, x, tau)
}

cqr_loss_cpp <- function(X, y, beta, alpha, tau) {
    .Call(`_RobustLRL_cqr_loss_cpp`, X, y, beta, alpha, tau)
}

calN_j_cpp <- function(n, j) {
    .Call(`_RobustLRL_calN_j_cpp`, n, j)
}

soft_thresholding_cpp <- function(x, t) {
    .Call(`_RobustLRL_soft_thresholding_cpp`, x, t)
}

SVT_cpp <- function(B, lambda) {
    .Call(`_RobustLRL_SVT_cpp`, B, lambda)
}

SVT_vec_cpp <- function(beta, d1, d2, lambda) {
    .Call(`_RobustLRL_SVT_vec_cpp`, beta, d1, d2, lambda)
}

